const minify = require("html-minifier").minify;
const { gzip } = require("node-gzip");

const { inlineScriptTags } = require("inline-scripts");
const inlineStylesheets = require("./node_modules/inline-scripts/src/inlineStylesheets");

const fs = require("fs");
const path = require("path");

async function init() {
  const js = await inlineScriptTags("./build/index.html");
  fs.writeFileSync(path.join(__dirname, "./build/index-bundle.html"), js);
  const css = await inlineStylesheets("./build/index-bundle.html");

  const minified = minify(css, {
    includeAutoGeneratedTags: true,
    removeAttributeQuotes: true,
    removeComments: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortClassName: true,
    useShortDoctype: true,
    collapseWhitespace: true,
  });

  fs.writeFileSync(path.join(__dirname, "./build/index-bundle.html"), minified);

  const ziped = await gzip(minified.toString());
  ensureDirectoryExistence('./build/gz/index-bundle.html.gz')
  fs.writeFileSync(
    path.join(__dirname, "./build/gz/index.html.gz"),
    ziped
  );
}

init();

function ensureDirectoryExistence(filePath) {
  var dirname = path.dirname(filePath);
  if (fs.existsSync(dirname)) {
    return true;
  }
  ensureDirectoryExistence(dirname);
  fs.mkdirSync(dirname);
}
